### ISSUE TITLE
buy and sell return None

### ISSUE THREAD

**Issue by loki-dv** [PyWaves/PyWaves#103]
Hello!

I try to post orders with buy and sell methods.

My code is very simple:

```
import pywaves as pw
privkey = 'privkey_here'
my_token = 'my_token_id_here'
myAddress = pw.Address(privateKey=privkey)
TOKEN = pw.Asset(my_token)
WAVES = pw.WAVES
TOKEN_WAVES = pw.AssetPair(TOKEN, WAVES)
myOrder = myAddress.buy(assetPair=TOKEN_WAVES, amount=1, price=1)
print(myOrder)
```

When it's executed I see None as order ID.

I tried to use different values of price and amount, the same result.

When I try to use amount like "1e8" I see an error:

```
Traceback (most recent call last):
  File "main.py", line 19, in <module>
    myOrder = myAddress.buy(assetPair=TOKEN_WAVES,
  File "/usr/local/lib/python3.8/site-packages/pywaves/address.py", line 766, in buy
    id = self._postOrder(assetPair.asset1, assetPair.asset2, b'\0', amount, normPrice, maxLifetime, matcherFee, timestamp)
  File "/usr/local/lib/python3.8/site-packages/pywaves/address.py", line 677, in _postOrder
    struct.pack(">Q", amount) + \
struct.error: required argument is not an integer
```

Also tried with Python 2 - the same (order post return None, but no errors about 1e8 numbers).

How I can post orders with the current version? Thanks.

**Comment by EmersonCaique** [comment]
Same problem

**Comment by and-89** [comment]
Same problem, when I try to post sell/buy order I get back "None" instead order Id

**Comment by juleznakamoto** [comment]
same

**Comment by cp3oDOTcom** [comment]
Try:
pw.MATCHER_PUBLICKEY = '9cpfKN9suPNvfeUNphzxXMjcnn974eme8ZhWUjaktzU5'

**Comment by schwab** [comment]
Verified... .setting pw.MATCHER_PUBLICKEY works and allows buy/sell to function correctly.  Note however it must be done AFTER any calls to pw.setMatcher().

**Comment by PyWaves** [comment]
Fixed in __init__.py
