### ISSUE TITLE
rounding issues on normPrice calculation

### ISSUE THREAD

**Issue by iammortimer** [PyWaves/PyWaves#109]
Randomly starting receiving errors along the lines of:
`[ERROR] Order Rejected - Invalid price, last 6 digits must be 0`

seems that pow (which is used for the calculation of normPrice) sometimes returns 9.99999999 when 10.0 is meant. A simple test:
`prices={0.00056328, 0.00056356, 0.00056384, 0.00056554, 0.00056639}`
`for price in prices:`
`    print("input: " +  str(price))`
`    price1 = pow(10, 8 + 8 - 2) * price`
`    print("pow: " + str(price1))`
`    price1 = round(pow(10, 8 + 8 - 2) * price)`
`    print("pow round: " + str(price1))`
`    normPrice = int(pow(10, 8 + 8 - 2) * price)`
`    print("normprice: " + str(normPrice))`
`    normPrice = int(round(pow(10, 8 + 8 - 2) * price))`
`    print("normprice round: " + str(normPrice))    `

Results from the test:

`input: 0.00056328`
`pow: 56328000000.0`
`pow round: 56328000000      `
`normprice: 56328000000`
`normprice round: 56328000000`
`input: 0.00056356`
`pow: 56355999999.99999`
`pow round: 56356000000`
`normprice: 56355999999`
`normprice round: 56356000000`
`input: 0.00056384`
`pow: 56384000000.0`
`pow round: 56384000000`
`normprice: 56384000000`
`normprice round: 56384000000`
`input: 0.00056554`
`pow: 56554000000.0`
`pow round: 56554000000`
`normprice: 56554000000`
`normprice round: 56554000000`
`input: 0.00056639`
`pow: 56638999999.99999`
`pow round: 56639000000`
`normprice: 56638999999`
`normprice round: 56639000000`

Problem can be quite easily fixed by changing the normprice calculation from:
`normPrice = int(pow(10, 8 + assetPair.asset2.decimals - assetPair.asset1.decimals) * price)`
to:
`normPrice = int(round(pow(10, 8 + assetPair.asset2.decimals - assetPair.asset1.decimals) * price))`
in address.py

**Comment by PyWaves** [comment]
Thanks! Done!
