### ISSUE TITLE
Maybe I am moron! lol

### ISSUE THREAD

**Issue by michaelsomerville** [PyWaves/PyWaves#11]
New to PY ( just fyi )

Created a index.py file with

```
#!/usr/bin/python 
import pywaves as pw
myAddress = pw.Address('XXX')
# get Waves balance
print("Your balance is %18d" % myAddress.balance())
# get Waves balance after 20 confirmations 
print("Your balance is %18d" % myAddress.balance(confirmations = 20))
# get an asset balance
print("Your asset balance is %18d" % myAddress.balance('XXX'))
```

added my address and I am getting 500 Internal error - added a htaccess
Options +ExecCGI 
AddHandler cgi-script .py

Checked that the VPS as python ... 

then tested .. 

#!/usr/bin/python 

print "Content-type: text/html\n\n"
print "How to run Python scripts in cPanel" 

^^^ worked fine.

So, did I miss a line or something to import the py configs ?

**Comment by PyWaves** [comment]
Seems to be an apache config problem, the script runs fine on command line.
