### ISSUE TITLE
no symbol found in whitelist

### ISSUE THREAD

**Issue by drinbs** [PyWaves/PyWaves#117]
I cannot get ticker information with example code.
Ticker becomes an error like this.

> {'reason': 'no symbol found in whitelist:WAVES/8LQW8f7P5d5PZM7GtZEBgaqRPGSzS3DfPuiXrURJ4AJS', 'type': 'Error'}

Could anyone help?

import pywaves as pw
WAVES_BTC = pw.AssetPair(pw.WAVES, pw.BTC)
ticker = WAVES_BTC.ticker()

**Comment by PyWaves** [comment]
Works fine for me. Did you use python3?

**Comment by drinbs** [comment]
Sorry. I should have updated the thread.
I now confirmed the code works perfectly.
Thanks.
