### ISSUE TITLE
BUG: not possible to generate new account

### ISSUE THREAD

**Issue by vlzhr** [PyWaves/PyWaves#118]
i'm trying to generate an account as is described in README:

![image](https://user-images.githubusercontent.com/22869641/80830335-7389a080-8bf1-11ea-98b7-20aac1b7deed.png)

**Comment by thartmann15** [comment]
Hi.
You are probably using python3. At the moment, using pywaves with python3 is broken. There exists a fix for python3 (https://github.com/PyWaves/PyWaves/pull/89/commits), but it is not yet merged. See also https://github.com/PyWaves/PyWaves/issues/127
