### ISSUE TITLE
Sending Ethereum to Other Ethereum Address (Invalid Address)

### ISSUE THREAD

**Issue by zackxiaoming** [PyWaves/PyWaves#12]
I did the following

myAddress = pw.Address(privateKey=wPrivate)
ethToken = pw.Asset('474jTeYx2r2Va35794tCScAXWJG9hU2HcgxzMowaZUnu')
myAddress.sendAsset(recipient=pw.Address('0xe85e4a16258a870d95e7f6908c38a40dd8637041'), token=ethToken, amount=float(amount))

I think the problem is if I insert a "Wave address" as my recipient it work, but if I insert a real "Ethereum" address, it will say invalid address.

Is there a way I can transfer my Ethereum to other ethereum wallet or my Bitcoin to other bitcoin wallet.

I hope to find a solution.

Thanks

**Comment by PyWaves** [comment]
Not possible like this, you have to send it via the gateway.
