### ISSUE TITLE
wrong example

### ISSUE THREAD

**Issue by alter** [PyWaves/PyWaves#123]
Example from README:

```
import pywaves as pw
# generate a new address
myAddress = pw.Address()

```

Real situation:
```Traceback (most recent call last):
  File "1.py", line 7, in <module>
    myAddress = pw.Address()
  File "/home/rdolgov/.local/lib/python3.8/site-packages/pywaves/address.py", line 229, in __init__
    raise ValueError('Empty private key not allowed')
ValueError: Empty private key not allowed
```

`$ python -V
Python 3.8.2`

`$ pip3 freeze |grep -i pywaves
PyWaves==0.8.33`

**Comment by thartmann15** [comment]
Hi.
You are probably using python3. At the moment, using pywaves with python3 is broken. There exists a fix for python3 (https://github.com/PyWaves/PyWaves/pull/89/commits), but it is not yet merged. See also #127 and #118

**Comment by PyWaves** [comment]
Will be update in the next release.
