### ISSUE TITLE
pywaves does not work with python3 correctly

### ISSUE THREAD

**Issue by thartmann15** [PyWaves/PyWaves#127]
Hi.

The problem are strings in python3. base58 outputs binary strings. This causes issues with the function wrapper().
Furthermore the string comparison is broken. Therefore one cannot call "Address()" to get a new address.

> import pywaves as pw
> a = pw.Address(privateKey=None)
       <- string comparison in python3 does not work as intended. this is a workaround to get it running
> a.balance()
      <-- this tries to call the url .../addresses/balance/b'3MvfHdhuJvX3w2R1rWmEi8KU3E8c5tYHtRD'
            and therefore fails

These two issues are already fixed in the pull request by BioMike
https://github.com/PyWaves/PyWaves/pull/89/commits
https://github.com/BioMike/PyWaves/tree/py3_address_binary_fixes
.
see also #118 and #123 which are refer to the same problem.

Please merge or fix it in another way.

**Comment by thartmann15** [comment]
On closer inspection, the base58 issue (binary string output for base58.b58decode) could be a problem with a missing version in requirements.txt as described in #116. The latest version of base58 is 2.0.1 which is incompatible with previous versions.

**Comment by PyWaves** [comment]
Empty privateKeys are not supported currently.
