### ISSUE TITLE
Transaction Error

### ISSUE THREAD

**Issue by geethsameer686** [PyWaves/PyWaves#13]
I am using local node waves testnet. transaction is not working. I posted the error. Please check it.
```
import pywaves as pw
pw.setNode(node = 'http://127.0.0.1:6869',chain = 'testnet')
address = '3Mq6YmrnfoSt5T36i3S2XPXpXh8kP87DUw4'
publicKey = '9u6mN4kN8U7iQVsyNaru7ko6VV3E3pQ6sqcmmDwM6k7a'
privateKey = 'GczfiQJoqkp4E4pXGj7wicx53nckPyG46EWChEd9brzM'
myAddress = pw.Address(privateKey=privateKey) 
t_id = myAddress.sendWaves(recipient=pw.Address('3MwMwdzo6k1wwDE8JgiZmbM7nXEL6xmftPc'),amount = 10000000)
```
Error: 
`{'error': 112, 'message': 'State check failed. Reason: invalid signature', 'tx': {'type': 4, 'id': 'BPP2CSFUBey5UybNDZpeeKJ7aEptMc2mXVmdYnUrAf3F', 'sender': '3Mq6YmrnfoSt5T36i3S2XPXpXh8kP87DUw4', 'senderPublicKey': '9u6mN4kN8U7iQVsyNaru7ko6VV3E3pQ6sqcmmDwM6k7a', 'fee': 100000, 'timestamp': 1521476122683, 'signature': '4PYFgEYtKJWG1zXQtmw3KMgR54opCnNBkfNQKieP4A6ywGNHainhfpNqnqhMwsoNeSW42C5kNyNs6K76tsSg1o3E', 'recipient': '3MwMwdzo6k1wwDE8JgiZmbM7nXEL6xmftPc', 'assetId': None, 'amount': 10000000, 'feeAsset': None, 'attachment': '1'}}`

**Comment by PyWaves** [comment]
Please test with latest version.
