### ISSUE TITLE
Switch market data to HTTPS?

### ISSUE THREAD

**Issue by me21** [PyWaves/PyWaves#15]
Market data URL is now encoded as https://github.com/PyWaves/PyWaves/blob/b3748cb0a8bd332111908be8c60f5c455642cda0/__init__.py#L41

Wouldn't it be more secure to access it over HTTPS?

**Comment by PyWaves** [comment]
Well, since this is public data anyway, i don't see a sense in using https here. Anyway, this would be an issue for the provider of the marketdata feed, not of the api.
