### ISSUE TITLE
Masspayment only works max 4 recipient?

### ISSUE THREAD

**Issue by dailydimaz** [PyWaves/PyWaves#16]
In my machine, mass payment script only work for max 4 recipient,
when i try more than 100, python said "too much address" 
but when i try to sent to 99, python have no feedback and comand line no hang, just back to 
>
and i try 90 recipient, 80,70,60,50,40,30,20,10,9,8,7,6,5,4.
just 4 recipient its work and recorded to blockchain
http://wavesexplorer.com/tx/DHKZUijrcindKSZfKQJ4h8uoJ2eBrrCdxLy1cJpaWN9D

the attachment is working,

and when i try airdrop script work smoothly too.

But problem is i want to sent proportional based on hodling x token and masspayment didn't work,
What script you suggest for me?

Thank you

**Comment by minevstrade** [comment]
I'm interested too... will let you know if i found solution

**Comment by SuperPaulTh** [comment]
Hey guys,
"The maximum number of recipients in a single transaction is 100" is documented [here](https://docs.wavesplatform.com/developers-guide/mass-transfer-transaction.html)

Anyway I also have trouble when using pywaves function massTransferAssets(transfer, array). I have enabled debug logging and get the following error:

_/transactions/broadcast 400 (Bad Request)_

My transfer array looks like this:
[
  {'recipient': '3Pxxx', amount: 5},
  {'recipient': '3Pxxx', amount: 5},
  (and so on)
]

Not sure if I'm doing something wrong or pywaves is building malformed json post data

**Comment by PyWaves** [comment]
Solved by latest version.
