### ISSUE TITLE
pw.WAVES assetID = ''

### ISSUE THREAD

**Issue by JackPickering** [PyWaves/PyWaves#3]
Hi there, 

I'm using a django backend to print out a report of how a current token is doing, when I attempt to use pw.WAVES as part of the assetPair in pw.AssetPair(pw.WAVES, pw.Asset('XYZ')), it returns the error: 
{u'status': u'error', u'message': u'Asset pair not available'}

When I simply print out the AssetPair it returns: 
asset1 = asset2 = XYZ

pw.WAVES returns nothing? Any ideas?

**Comment by rszalski** [comment]
Instead of `pw.WAVES` try using `pw.Asset('WAVES')`, does it work?
