### ISSUE TITLE
Example code don't work

### ISSUE THREAD

**Issue by ffbskt** [PyWaves/PyWaves#30]
myAddress.buy(...) get error " TypeError: b'H9sXEScHzMhhmpcCpkS7FQwZfxa69vYV56TGNwGmyD8G' is not JSON serializable   "
I think because you put at json.dumps({  }) byte code from  crypto.sign function which return bytecode

**Comment by BarabanovV** [comment]
hi! problem in the base58. You need to roll back to pip install base58 == 0.2.5
