### ISSUE TITLE
Wrong response from AssetPair.orderbook()

### ISSUE THREAD

**Issue by superoleg421** [PyWaves/PyWaves#31]
I want to save orderbook's data from wavesplatform. I try to send request one time per 10 sec. Almost always all is OK, but sometimes I'm getting error while parsing orderbook JSON about one hundred times in a row:
`Expecting value: line 1 column 1 (char 0)`
When I tried to look at response at these moments, I saw next message:
`An error occurred: Ask timed out on [Actor[akka://wavesplatform/user/matcher#-1822518904]] after [5000 ms]. Sender[null] sent message of type "com.wavesplatform.matcher.market.OrderBookActor$GetOrderBookRequest".
`
Is it my local problem or something wrong with WAVES node? Can you help please?

**Comment by PyWaves** [comment]
Looks like a problem on the waves node.
