### ISSUE TITLE
massTransferAssets 

### ISSUE THREAD

**Issue by Diegoescalonaro** [PyWaves/PyWaves#42]
Hi,

I'm trying to implement the "massTransferAssets" function in a python script but there is a problem that doesn't allow me to get it.

I use:   **myAddress.massTransferAssets(transfers, pywaves.Asset('Token_ID'))**

"myAddress" and "transfers" are OK because when I use them with "massTransferWaves" it runs.

So, anyone has the same problem?

**Comment by jansenmarc** [comment]
For me it works, what error do you get?
