### ISSUE TITLE
asset decimals for orders are not calculated properly after asset normprice edited

### ISSUE THREAD

**Issue by sabotagebeats** [PyWaves/PyWaves#54]
https://github.com/PyWaves/BlackBot/issues/12
I believe this is being caused by improper calculation of decimals introduced here: 
https://github.com/PyWaves/PyWaves/commit/055cad545c0d5ca101ad421c63c1a88b5966fc56
cc @PyWaves @jansenmarc

**Comment by sabotagebeats** [comment]
I believe I have fixed this here, please review: https://github.com/PyWaves/PyWaves/pull/55

**Comment by sabotagebeats** [comment]
so unfortunately it looks like this didn't fully fix the problem. 

https://github.com/PyWaves/PyWaves/pull/55#issuecomment-417182574

**Comment by tflink** [comment]
Isn't the original code correct? The docs say that price is supposed to be "10^(8+marketDecimals-assetDecimals)" . Am I reading this incorrectly?

https://docs.wavesplatform.com/en/development-and-api/dex-api/matcher.html

**Comment by tflink** [comment]
Are there any examples of asset pairs which don't work with the old 10^(8+market-asset) method for calculation?

Looking at some of the other API libraries, [WavesCS seems to leave the 8 in there](https://github.com/wavesplatform/WavesCS/blob/master/WavesCS/Assets.cs#L41) but [WavesJ seems to just expect you to know what math to do](https://github.com/wavesplatform/WavesJ/blob/master/examples/src/main/java/NodeExample.java#L89)

**Comment by PyWaves** [comment]
I'm calculating the price like the following in one of my bots:

    lowestAsk = int(orderbook['asks'][0]['price'] / (10 ** (tradingPair.asset2.decimals - tradingPair.asset1.decimals)))

But i have not tested if that is working for all assets...

**Comment by tflink** [comment]
Is that `lowestAsk` the number you use as the price arg for `address.buy`?

**Comment by PyWaves** [comment]
Yes

**Comment by tflink** [comment]
I ran a quick code snippet to look at prices and asset decimals:
```
import pywaves

for symbol in pywaves.symbols():
    thisasset = pywaves.Asset(symbol['assetID'])
    
    if thisasset.decimals != 8:
        thisassetpair = pywaves.AssetPair(pywaves.WAVES, thisasset)
        orderbook = thisassetpair.orderbook()
        
        if len(orderbook['asks']) == 0 or len(orderbook['bids']) == 0:
            continue
            
        print("Asset {} has decimals {}".format(symbol['symbol'], thisasset.decimals))
        print("  first ask price: {}".format(orderbook['asks'][0]['price']))
        print("  first bid price: {}".format(orderbook['bids'][0]['price']))
```
[Output when I ran it on 20181030](https://gist.github.com/tflink/f33eea557702a284334bedcc9c762521)

It looks like most symbols that WAVDEX lists have `decimals = 8` and with the exception of non-crypto currencies (EUR and USD), the symbols where `symbols != 8` are all oddball things that don't show up in the WAVESDEX web client. Not sure I see a pattern for those 

I'm wondering if we can do something like the following:

- if one of the assets is EUR or USD, use `decimals = 2`
- if `decimals == 8` for both symbols, use raw price from orderbook
- if 'decimals !=8`for either symbol, either special case all the outliers or just throw an exception and don't continue the transaction

Any thoughts?

**Comment by PyWaves** [comment]
No, it is not a good idea to hardcode this. There are assets out there with different amounts of decimals. Therefore, we need a general solution for this. Did the code that i posted above not work for you?

**Comment by tflink** [comment]
I'm not generally an advocate of hard coding things but I'm not thinking of another way to get all the asset pairs to work.

The code you posted works for most assets but one of the exceptions is whenever USD or EUR are involved.

I'm starting with the following function
```
def do_sale(asset1, asset2, amount, price):
    real_amount = int(round(amount * pow(10,asset1.decimals)))

    price_factor =  asset2.decimals - asset1.decimals
    print("price_factor: {}".format(price_factor))
    real_price = price * pow(10, price_factor)

    assetpair = pywaves.AssetPair(asset1, asset2)
    asset1_name = asset1.name or 'WAVES'
    asset2_name = asset2.name or 'WAVES'
    print("Selling {} {} for {} {}/{}".format(real_amount, asset1_name, real_price, asset2_name, asset1_name))
    address.sell(assetpair, real_amount, real_price, 300, matcherFee=pywaves.DEFAULT_MATCHER_FEE)
```
If I want to sell .001 BTC for 6642.20 USD/BTC, I do the following:
```
do_sale(pywaves.BTC, pywaves.USD, 0.001, 6642.20)
```
Which gives me the output of:
```
price_factor: -6
Selling 100000 b'WBTC' for 0.006642199999999999 b'WUSD'/b'WBTC'
[ERROR] Order Rejected - Invalid order
```
The only way I can get this sell to be at the correct price is when `price_factor = -2` but I don't see a sane way to make that happen.

That being said, it appears to work when I use 2 assets that have `decimals = 8`:
```
do_sale(pywaves.WAVES, pywaves.BTC, 0.5, 0.00028850)
```
Which gives the output of:
```
price_factor: 0
Selling 50000000 WAVES for 0.0002885 b'WBTC'/WAVES
2018-10-31 14:33:55,911 Order Accepted - ID: xxxxx
```
This creates a sell order with the prices that I intended.

I'm pretty sure that I'm using the same calculation you listed above and it does work with most assets but I don't see how it can work with USD or EUR. Do you see anything wrong with that example function or suggestions as to how to make it work for the BTC/USD?

**Comment by PyWaves** [comment]
You can of course do something like this in your code, but i won't implement it in the framework.
