### ISSUE TITLE
Installation Issue - python-axolotl-curve25519 dependency

### ISSUE THREAD

**Issue by toddry** [PyWaves/PyWaves#59]
I am having issues installing PyWaves. The dependency for python-axolotl-curve25519 is where the installation is failing. 

I have installed the latest version of VS Community and have the Data Tools and Visual C++ for Python packages.

**Notable Error Messages:**

```
curve/curve25519-donna.c(49) : fatal error C1083: Cannot open include file: 'stdint.h': No such file or directory
  error: command 'C:\\Users\\Command Center\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\amd64\\cl.exe' failed with exit status 2
```

`Command "c:\python27\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\comman~1\\appdata\\local\\temp\\pip-install-dnebcs\\python-axolotl-curve25519\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record c:\users\comman~1\appdata\local\temp\pip-record-y36sug\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in c:\users\comman~1\appdata\local\temp\pip-install-dnebcs\python-axolotl-curve25519\`

![image](https://user-images.githubusercontent.com/44851379/48508730-91502380-e80c-11e8-94d1-56610cd4cf41.png)

**Comment by toddry** [comment]
I have also tried installing pywaves using Python 3.7 with a similar error.

`C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE\stdint.h(44): error C2632: '__int64' followed by 'long' is illegal
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE\stdint.h(44): warning C4091: 'typedef ': ignored on left of '__int64' when no variable is declared
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE\stdint.h(45): warning C4114: same type qualifier used more than once
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE\stdint.h(45): error C2632: '__int64' followed by 'long' is illegal
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE\stdint.h(45): warning C4091: 'typedef ': ignored on left of 'unsigned __int64' when no variable is declared
    curve25519module.c(51): warning C4244: 'function': conversion from 'Py_ssize_t' to 'const unsigned long', possible loss of data
    curve25519module.c(78): warning C4244: 'function': conversion from 'Py_ssize_t' to 'const unsigned long', possible loss of data
    curve25519module.c(157): warning C4047: 'initializing': 'Py_ssize_t' differs in levels of indirection from 'void *'
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2`

**Comment by PyWaves** [comment]
Did you try to google the error and apply solutions found by this? E.g., i found the following three solutions that might also help you:

https://stackoverflow.com/questions/39358876/visual-c-for-python-failed-with-exit-status-2
https://github.com/sammchardy/python-binance/issues/148
https://intellij-support.jetbrains.com/hc/en-us/community/posts/360000034884-pip-install-mysql-Error-error-command-C-Program-Files-x86-Microsoft-Visual-Studio-2017-BuildTools-VC-Tools-MSVC-14-12-25827-bin-HostX86-x86-cl-exe-failed-with-exit-status-2

**Comment by toddry** [comment]
Thanks for the response. I went through the troubleshooting process recommended in the first link without luck. 

Working on researching the stdint.h error, as I believe this is the root problem/

**Comment by toddry** [comment]
I downloaded stdint.h from https://github.com/mattn/gntp-send/blob/master/include/msinttypes/stdint.h, which allows me to get past the first error.

This got me past the stdint.h error which allowed me to install PyWaves on Python 3.7. Still getting the error on v2.7, but a newer version of Python will suffice for this script.

**Comment by kidstell** [comment]
i had similar issue. look at the comment here for resolution
mukulhase/WebWhatsapp-Wrapper#211 (comment)
