### ISSUE TITLE
Wrong default tx fee for sponsored transaction

### ISSUE THREAD

**Issue by DrBlast** [PyWaves/PyWaves#61]
`  def sendAsset(self, recipient, asset, amount, attachment='', feeAsset='', txFee=pywaves.DEFAULT_TX_FEE, timestamp=0):`
if user sets sponsoredAsset to  feeAsset and not sets txFee, you should send request for asset details and get minSposoredFee instead of using DEFAULT_TX_FEE.
minSposoredFee could be less or more then default one.

For example, if minSposoredFee = 10_000 and user not sets txFee, then tx will cost 0.01 waves
if minSposoredFee = 1_000_000 then default txFee will be less then minimal

**Comment by PyWaves** [comment]
Well, i think that would be a nice solution if the standard API would support to get the current minSponsoredFee.

**Comment by DrBlast** [comment]
You can get current minSponsoredFee using assets/details endpoint

**Comment by PyWaves** [comment]
Are the other APIs (JavaScript, Java, ...) also behaving like this? I think we should try to get some standard behaviour in the API's.

**Comment by DrBlast** [comment]
We will make the same  changes in WavesJ and WavesCS libs. As sponsored fee is custom for each asset we cannot set any default value for this case.
Also asset can be scripted, in WavesCS we already get info about it and get extra fee = 0.004 by default. I can describe a detailed task with all "if" cases the same for all libs.
In spite of this, default tx fee = 100_000 is wrong if feeAsset is not null

**Comment by PyWaves** [comment]
Implemented!
