### ISSUE TITLE
error with MassTransferTransaction when using 139 byte attachment

### ISSUE THREAD

**Issue by vladislavpetushkov** [PyWaves/PyWaves#66]
Hello! I Have got an error when try to send mass transfer asset transaction with attachment 139 byte.
'error': 112, 'message': 'State check failed. Reason: Fee in WAVES for com.wavesplatform.transaction.transfer.MassTransferTransaction does not exceed minimal value of 5500000 WAVES: 5100000'

**Comment by vladislavpetushkov** [comment]
For transfer smart asset we need to add  0.004 WAVES

**Comment by PyWaves** [comment]
Fixed!
