### ISSUE TITLE
Generate a new address error

### ISSUE THREAD

**Issue by kernelpanic2015** [PyWaves/PyWaves#68]
# generate a new address
``
import pywaves as pw
``
``
myAddress = pw.Address()  
``

Error Message:
myAddress = pw.Address()
 File ".../address.py", line 225, in __init__
    raise ValueError('Empty private key not allowed')
ValueError: Empty private key not allowed

**Comment by ivaox** [comment]
I have the same error

**Comment by PyWaves** [comment]
This is not a bug.

**Comment by ivaox** [comment]
How do I resolve this, to what is it due?

**Comment by PyWaves** [comment]
We had some trouble in connection with gateways while generating new addresses with empty private keys. The usual workaround is to generate a new seed and generate an address from this seed. By this, the client is explicitely in full controll of the necessary credentials.

**Comment by sabotagebeats** [comment]
[https://github.com/PyWaves/PyWaves/#generate-a-new-address](url)
it says in the readme.md that this should work - how do you generate new seed?

**Comment by sabotagebeats** [comment]
[](https://github.com/PyWaves/PyWaves/#generate-a-new-address)
it says in the readme.md that this should work - how do you generate new seed?

**Comment by sabotagebeats** [comment]
> We had some trouble in connection with gateways while generating new addresses with empty private keys. The usual workaround is to generate a new seed and generate an address from this seed. By this, the client is explicitely in full controll of the necessary credentials.
[https://github.com/PyWaves/PyWaves/#generate-a-new-address
](https://github.com/PyWaves/PyWaves/#generate-a-new-address)
it says in the readme.md that this should work - how do you generate new seed?
