### ISSUE TITLE
Getting sum amount of  orderbook 

### ISSUE THREAD

**Issue by karmenali** [PyWaves/PyWaves#7]
I am trying to get all order from 'amount'  waves_usd pair. I did it. now I want to use that value to calculate  orders amount but I got an error: 'float' object is not iterable
İn the below codes without sum(x) 'print(x) working fine and type(x) = floats
how can I get sum() function works.

`import pywaves as pw

usd = 'Ft8X1v1LTa1ABafufpaCWyVj8KkaxUWE6xBhW6sNFJck'

WavesUsd = pw.AssetPair(pw.WAVES, pw.Asset(usd))

a = WavesUsd.orderbook()['bids']

for i in a:
    x = (i['amount'] / 100000000)
    print(sum(x))
`

**Comment by rszalski** [comment]
[sum](https://docs.python.org/3.6/library/functions.html#sum) works on _iterables_ and you are passing it a float in each loop iteration. You cannot iterate over a float.

You have to first convert all the _amounts_ and then sum them, e.g.:

    amounts = []
    for i in a:
        x = (i['amount'] / 100000000)
        amounts.append(x)

    # Outside the loop
    print(sum(amounts))

Or more pythonic: `print(sum(i['amount'] / 100000000 for i in a))`
