### ISSUE TITLE
myAddress.issueAsset doesn't work

### ISSUE THREAD

**Issue by j0k** [PyWaves/PyWaves#72]
I use code as in example in README.md.
```
import pywaves as pw
node = "https://testnode1.wavesnodes.com"
chain = "testnet"

pw.setNode(node = node, chain = chain)
myAddress = pw.Address(privateKey='...')

myAddress.sendWaves(otherAddress, 10000000)
myToken = myAddress.issueAsset('Token1', 'My Token', 1000, 0)
s = myToken.status()
print(s)
```
raised:
```
----> 9 myToken = myAddress.issueAsset('Token1', 'My Token', 1000, 0)
     10 s = myToken.status()
     11 print(s)

e:\ProgramData\Anaconda3\lib\site-packages\pywaves\address.py in issueAsset(self, name, description, quantity, decimals, reissuable, txFee)
    337                 return req
    338             else:
--> 339                 return pywaves.Asset(req['assetId'])
    340 
    341     def reissueAsset(self, Asset, quantity, reissuable=False, txFee=pywaves.DEFAULT_TX_FEE):

KeyError: 'assetId'
```

**Comment by BioMike** [comment]
The code returns an error, which has a different format than what the code expects (the reply below is generated with a throw-away address):

{u'message': u'State check failed. Reason: negative waves balance: 3P23MWvmmMDvbvF2TWZYDscCCLvcN5ZULU9, old: 0, new: -100000000',
 u'tx': {u'reissuable': False, u'fee': 100000000, u'description': u'My Token', u'timestamp': 1566542641437, u'assetId': u'HSRDjKnWPU8NNcSS6EZf8C5tmyH7e9cwwrCEHHqMM3wn', u'decimals': 0, u'feeAssetId': None, u'senderPublicKey': u'HBDRim9s1cKw1nKEvKRUZKVeqqhGjCxDewB3Qjx81qVu', u'name': u'Token1', u'version': 1, u'sender': u'3P23MWvmmMDvbvF2TWZYDscCCLvcN5ZULU9', u'signature': u'5aH9amLh26Yy2ZJnGWPrnXSFdbETvbpg4zkWp89HaPtDVRP8tiWJ6tsJzesGCjuBzCJfs7qywaDdUezv4qukxkMi', u'proofs': [u'5aH9amLh26Yy2ZJnGWPrnXSFdbETvbpg4zkWp89HaPtDVRP8tiWJ6tsJzesGCjuBzCJfs7qywaDdUezv4qukxkMi'], u'type': 3, u'id': u'HSRDjKnWPU8NNcSS6EZf8C5tmyH7e9cwwrCEHHqMM3wn', u'quantity': 1000}, u'trace': [], u'error': 112}

So, in my opinion the best way to resolve this would be to return the error in this case and the asset when succesful (which might need to have the ['assedID'] key changed to ['tx']['AssetId']).
