### ISSUE TITLE
Loop to see balances

### ISSUE THREAD

**Issue by fmarzolo** [PyWaves/PyWaves#83]
I am now able to iterate in the token list and show something similar to every token balance.
It seems that the balance is not the expected one.
Last row is not able to get me the decimal adjusted balance, or it shows 99999999 for the number 1.

In waves explorer I get 

DtHrdJwXovcVDzhuAwpWM9...  Ktoken  1.00
while pywaves:
Token name: b'Ktoken', Address: DtHrdJwXovcVDzhuAwpWM9..., Decimals:2, or :100
balance: 999999.0

In waves explorer i get
53VHGAEfVNJnByeMbu9… Auct token 2000.00000000
while in pywaves:
Token name: b’Auct token’, Address: 53VHGAEfVNJnByeMbu9…, Decimals:8, or :100000000
balance: 350000000.0

What is going on? And what is the b’’ surrounding the token name?

`import pywaves as pw

myAddress = pw.Address(privateKey='prikey')
print("Public key:" + myAddress.publicKey)
print("Your balance without decimals is %18d" % myAddress.balance())
print("Your balance is %18f" % (myAddress.balance() / pw.WAVES.decimals))

print("Assets no: %d" % len(myAddress.assets()))
for assetAddress in myAddress.assets():
    aToken=pw.Asset(assetAddress)
    print("Token name: %s" % aToken.name, end=", ")
    print("Address: %s" % assetAddress, end=", ")
    #print("descr: " + str(aToken.description))
    print("Decimals:" + str(aToken.decimals) + ", or :" + str(10**aToken.decimals))
    print("balance: " + str(float(aToken.quantity) / pow(10, aToken.decimals)))
`

**Comment by PyWaves** [comment]
Can you please send me an example address with the asset id you are checking?

**Comment by fmarzolo** [comment]
I get an address from explorer (not mine)
try with this code, you will see the following first line output, but in explorer you will see:
C9XD25wtUf4MTqbyDX8zqxpY2aXk6recZd5Bwtq7CUJS  Fahari cash coin  0.00016480

My output:
Waves decimals: 8
Your balance without decimals is          275655722
Your balance is           2.756557
Assets no: 341
Token name: b'Fahari cash coin', Address: C9XD25wtUf4MTqbyDX8zqxpY2aXk6recZd5Bwtq7CUJS, Decimals:8, or :100000000
balance: 18000000.0,  raw balance: 1800000000000000
and so on

`import  pywaves as pw

decimalDivisor=float(pow(10,pw.WAVES.decimals))
myAddress = pw.Address(address='3P73aEqSgUrx8mup6ovTWJnHNTC3MaVauMt')
print("Waves decimals: %d" % pw.WAVES.decimals)
if len(myAddress.publicKey)>0:
   print("Public key:" + myAddress.publicKey)
print("Your balance without decimals is %18d" % myAddress.balance())
print("Your balance is %18f" % (myAddress.balance() / decimalDivisor))

if len(myAddress.assets())==0:
   print("no other asset contained")
else:
   print("Assets no: %d" % len(myAddress.assets()))
   #print(myAddress.assets)
   for assetAddress in myAddress.assets():
      aToken=pw.Asset(assetAddress)
      print("Token name: %s" % aToken.name, end=", ")
      print("Address: %s" % assetAddress, end=", ")
      #print("descr: " + str(aToken.description))
      print("Decimals:" + str(aToken.decimals) + ", or :" + str(10**aToken.decimals))
      print("balance: " + str(float(aToken.quantity) / pow(10, aToken.decimals)),end=", ")
      print("raw balance: " + str(aToken.quantity))
`

**Comment by PyWaves** [comment]
Your code is wrong. Address.balance() returns the correct balance of an address for an asset.
