### ISSUE TITLE
WAVES quntity bug

### ISSUE THREAD

**Issue by vlzhr** [PyWaves/PyWaves#94]
Both `pw.Asset("WAVES")` and `pw.WAVES` do return quntity=10000000000000000

Nowadays, this is not true ;-) 
Could you update this method to use https://nodes.wavesnodes.com/api-docs/index.html#!/rewards/rewards_1 for getting actual WAVES quantity?

**Comment by PyWaves** [comment]
Fixed on github, will be included in the next release on pypi.
